version: '3.3'
services:
  proxy:
    ports:
      - 80:80
    build:
      dockerfile: Dockerfile
      context: reverseProxy
    depends_on:
      - gateway    
  gateway:
    build:
      dockerfile: Dockerfile
      context: gateway
    depends_on:
      - questions
      - answers
  files-db:
    image: mysql
    volumes:
      - files-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=files
  files:
    build:
      dockerfile: Dockerfile
      context: files
    volumes:
      - ./uploads:/files
  answers:
    build:
      dockerfile: Dockerfile
      context: answers
  questions:
    depends_on:
      - answers
    build:
      dockerfile: Dockerfile
      context: questions
    restart: on-failure
  frontend:
    build:
      dockerfile: Dockerfile
      context: frontend
    depends_on:
      - proxy
volumes:
  files-data: