version: '3.3'
services:
  proxy:
    ports:
      - 80:80
    build:
      dockerfile: Dockerfile
      context: reverseProxy
    depends_on:
      - gateway    
  gateway:
    build:
      dockerfile: Dockerfile
      context: gateway
    depends_on:
      - questions
      - answers
  files-db:
    image: mysql
    volumes:
      - files-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=files
  files:
    build:
      dockerfile: Dockerfile
      context: files
    volumes:
      - ./uploads:/files
    depends_on:
      - files-db
    restart: on-failure:2
  answers-db:
    image: mysql
    volumes:
      - answers-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=answers
  answers:
    build:
      dockerfile: Dockerfile
      context: answers
    depends_on:
      - answers-db
    restart: on-failure:2
  questions-db:
    image: mysql
    volumes:
      - questions-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=questions
  questions:
    depends_on:
      - answers
      - questions-db
    build:
      dockerfile: Dockerfile
      context: questions
    restart: on-failure:2
  frontend:
    build:
      dockerfile: Dockerfile
      context: frontend
    depends_on:
      - proxy
volumes:
  files-data:
  answers-data:
  questions-data: