version: '3.3'
services:
  proxy:
    ports:
      - 80:80
    build:
      dockerfile: Dockerfile
      context: ReverseProxy
    depends_on:
      - gateway
  gateway:
    build:
      dockerfile: Dockerfile
      context: Gateway
    depends_on:
      - questions
      - answers
  answers:
    build:
      dockerfile: Dockerfile
      context: Answers
  questions:
    depends_on:
      - answers
    build:
      dockerfile: Dockerfile
      context: Questions
    healthcheck:
      test: ["CMD", "ping", "answers"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  frontend:
    build:
      dockerfile: Dockerfile
      context: Frontend
    depends_on:
      - proxy